package lab

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Verdict groups items into one clause of the acceptance gate.
type Verdict struct {
	Name  string
	Items []string
}

// Verdicts are the four independent verdicts from section 42 of the test plan.
func Verdicts() []Verdict {
	return []Verdict{
		{
			Name: "LYMPH_EVENT_CORE_VALIDATED",
			Items: []string{
				"S01_lab", "S02_unrelated", "S09_lineage", "S14_duplicate",
				"S15_collision", "S17_clock", "S36_grouping",
			},
		},
		{
			Name: "LYMPH_ADAPTATION_ROUTING_VALIDATED",
			Items: []string{
				"S03_agent", "S04_mcp", "S05_ml", "S06_ingest", "S07_generic",
				"S08_artifact", "S19_worker_death", "S20_bad_output",
				"S29_multi_issue", "S30_not_a_config", "S37_routing",
			},
		},
		{
			Name: "LYMPH_CONFIG_GOVERNANCE_VALIDATED",
			Items: []string{
				"S12_stale", "S16_installation", "S22_wrong_target", "S24_sqlite_rebuild",
				"S26_rollback", "S27_late_regression", "S28_schema_migration",
				"S38_versioning", "S39_reproducibility",
			},
		},
		{
			Name: "LYMPH_RESILIENCE_VALIDATED",
			Items: []string{
				"S10_chaos", "S11_deploy_kill", "S13_concurrent", "S18_unavailable",
				"S21_manual_edit", "S23_disk_full", "S25_corrupt_ledger", "S31_fuzz",
				"S32_state_fuzz", "S33_soak", "S34_performance", "S35_zeroes",
				"S40_disaster",
			},
		},
	}
}

// FinalGate is the last line of the acceptance gate.
const FinalGate = "LYMPH_001_READY_FOR_SHADOW_INTEGRATION"

// ProtocolVerdicts are the L2.6 client/session/socket verdicts. They are graded
// separately from the deployment gate on purpose: passing them says the
// integration protocol works, not that Lymph may change a production system
// (mission sections 97, 98, 129).
func ProtocolVerdicts() []Verdict {
	return []Verdict{
		{Name: "LYMPH_CLIENT_PROTOCOL_VALIDATED", Items: []string{"P01_protocol"}},
		{Name: "LYMPH_SESSION_IDENTITY_VALIDATED", Items: []string{"P02_session_identity"}},
		{Name: "LYMPH_RECONNECT_SPOOL_VALIDATED", Items: []string{"P03_reconnect_spool"}},
		{Name: "LYMPH_SOCKET_ISOLATION_VALIDATED", Items: []string{"P04_socket_isolation"}},
	}
}

// VerdictResult grades one verdict.
type VerdictResult struct {
	Name     string   `json:"name"`
	Passed   bool     `json:"passed"`
	Missing  []string `json:"missing,omitempty"`
	Blockers []string `json:"blockers,omitempty"`
}

// Evaluate computes the verdicts from the recorded items.
func (r *Report) Evaluate() []VerdictResult {
	return evaluate(r, Verdicts())
}

// EvaluateProtocol computes the client/session/socket verdicts.
func (r *Report) EvaluateProtocol() []VerdictResult {
	return evaluate(r, ProtocolVerdicts())
}

// evaluate grades one group of verdicts against the recorded items. Every
// verdict group is computed the same way, so a new group cannot quietly grade
// itself more leniently than the others.
func evaluate(r *Report, verdicts []Verdict) []VerdictResult {
	items := map[string]Item{}
	for _, item := range r.Items() {
		items[item.ID] = item
	}

	var results []VerdictResult
	for _, verdict := range verdicts {
		result := VerdictResult{Name: verdict.Name, Passed: true}
		for _, id := range verdict.Items {
			item, ok := items[id]
			if !ok {
				result.Passed = false
				result.Missing = append(result.Missing, id+" (not run)")
				continue
			}
			switch item.Status {
			case StatusPass:
			case StatusBlocked:
				result.Passed = false
				result.Blockers = append(result.Blockers, id+": "+item.Detail)
			default:
				result.Passed = false
				result.Missing = append(result.Missing, id+" ("+string(item.Status)+")")
			}
		}
		results = append(results, result)
	}
	return results
}

// ProtocolReady reports whether every client-protocol verdict passed.
func (r *Report) ProtocolReady() bool {
	for _, result := range r.EvaluateProtocol() {
		if !result.Passed {
			return false
		}
	}
	return true
}

// Ready reports the final gate.
func (r *Report) Ready() bool {
	for _, result := range r.Evaluate() {
		if !result.Passed {
			return false
		}
	}
	return true
}

// Failed reports whether any item is a defect.
func (r *Report) Failed() int { return r.Counts()[StatusFail] }

// Markdown renders the human report.
func (r *Report) Markdown() string {
	var b strings.Builder
	counts := r.Counts()

	b.WriteString("# Lymph Lab report\n\n")
	b.WriteString("Generated by `go test ./lab/...` — one line per item from the test plan.\n\n")
	fmt.Fprintf(&b, "Graded: %d items — PASS %d, FAIL %d, PARTIAL %d, BLOCKED %d, SKIPPED %d\n\n",
		len(r.Items()), counts[StatusPass], counts[StatusFail], counts[StatusPartial],
		counts[StatusBlocked], counts[StatusSkipped])
	b.WriteString("PASS is evidence. FAIL is a defect. BLOCKED is capability this build does not have — ")
	b.WriteString("it is a scope statement, not a passing grade.\n\n")

	b.WriteString("| Item | Spec | Status | Evidence |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, item := range r.Items() {
		evidence := item.Evidence
		if evidence == "" {
			evidence = item.Detail
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", item.ID, item.Spec, item.Status, escapePipes(evidence))
	}

	b.WriteString("\n### Supporting evidence\n\n")
	b.WriteString("Detailed tests behind the grades above. They run, and fail the build, exactly like the graded items; ")
	b.WriteString("they are listed here rather than as rows so the summary stays readable.\n\n")
	for _, item := range r.Items() {
		if len(item.Supporting) == 0 {
			continue
		}
		fmt.Fprintf(&b, "**%s**\n\n", item.ID)
		for _, note := range item.Supporting {
			fmt.Fprintf(&b, "- %s\n", escapePipes(note))
		}
		b.WriteString("\n")
	}

	b.WriteString("\n## Verdicts\n\n")
	for _, result := range r.Evaluate() {
		status := "NOT VALIDATED"
		if result.Passed {
			status = "VALIDATED"
		}
		fmt.Fprintf(&b, "### %s — %s\n\n", result.Name, status)
		for _, missing := range result.Missing {
			fmt.Fprintf(&b, "- not satisfied: %s\n", missing)
		}
		for _, blocker := range result.Blockers {
			fmt.Fprintf(&b, "- blocked: %s\n", blocker)
		}
		if result.Passed {
			b.WriteString("- every item in this group passed\n")
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "### %s — %s\n\n", FinalGate, map[bool]string{true: "READY", false: "NOT READY"}[r.Ready()])
	b.WriteString("The lab uses synthetic fixtures only and grants no production authority.\n")

	b.WriteString("\n## Client protocol verdicts (L2.6)\n\n")
	b.WriteString("Graded separately: passing these says the integration protocol works, ")
	b.WriteString("not that Lymph may change a running system.\n\n")
	for _, result := range r.EvaluateProtocol() {
		status := "NOT VALIDATED"
		if result.Passed {
			status = "VALIDATED"
		}
		fmt.Fprintf(&b, "### %s — %s\n\n", result.Name, status)
		for _, missing := range result.Missing {
			fmt.Fprintf(&b, "- not satisfied: %s\n", missing)
		}
		for _, blocker := range result.Blockers {
			fmt.Fprintf(&b, "- blocked: %s\n", blocker)
		}
		if result.Passed {
			b.WriteString("- every item in this group passed\n")
		}
		b.WriteString("\n")
	}
	if ready := r.ProtocolReady(); ready {
		b.WriteString("### CLIENT_PROTOCOL_READY — READY\n\n")
		b.WriteString("Applications can integrate through one local socket, identify themselves, ")
		b.WriteString("obtain sessions, survive daemon outages and replay safely. Separate from ")
		b.WriteString("`LYMPH_001_READY_FOR_SHADOW_INTEGRATION`, which still requires L3.\n")
	} else {
		b.WriteString("### CLIENT_PROTOCOL_READY — NOT READY\n")
	}

	return b.String()
}

func escapePipes(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
}

// Write emits report.json and REPORT.md into dir.
func (r *Report) Write(dir string) (string, string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", "", err
	}

	type payload struct {
		Items            []Item          `json:"items"`
		Verdicts         []VerdictResult `json:"verdicts"`
		Ready            bool            `json:"ready_for_shadow_integration"`
		Counts           map[Status]int  `json:"counts"`
		ProtocolVerdicts []VerdictResult `json:"protocol_verdicts"`
		ProtocolReady    bool            `json:"client_protocol_ready"`
	}
	body, err := json.MarshalIndent(payload{
		Items:            r.Items(),
		Verdicts:         r.Evaluate(),
		Ready:            r.Ready(),
		Counts:           r.Counts(),
		ProtocolVerdicts: r.EvaluateProtocol(),
		ProtocolReady:    r.ProtocolReady(),
	}, "", "  ")
	if err != nil {
		return "", "", err
	}
	jsonPath := filepath.Join(dir, "report.json")
	if err := os.WriteFile(jsonPath, append(body, '\n'), 0o644); err != nil {
		return "", "", err
	}
	mdPath := filepath.Join(dir, "REPORT.md")
	if err := os.WriteFile(mdPath, []byte(r.Markdown()), 0o644); err != nil {
		return "", "", err
	}
	return jsonPath, mdPath, nil
}
